-- noinspection SqlResolveForFile @ routine/"gen_random_uuid"

DROP TABLE IF EXISTS users_roles_xref;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
    id          INTEGER         PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email       VARCHAR(100)    NOT NULL,
    password    VARCHAR(100)    DEFAULT NULL,
    firstName   VARCHAR(100)    NOT NULL,
    lastName    VARCHAR(100)    NOT NULL,
    active      BOOLEAN         NOT NULL
);

CREATE UNIQUE INDEX users_username_idx ON users (email);

CREATE TABLE IF NOT EXISTS sessions (
    id          UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    userid      INTEGER         DEFAULT NULL REFERENCES users (id),
    key_vals    JSONB           NOT NULL DEFAULT '{}'::jsonb,
    expires     TIMESTAMP       NOT NULL
);

CREATE UNIQUE INDEX session_userid_idx ON sessions (userid);

CREATE TABLE IF NOT EXISTS roles (
    id          INTEGER         PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    role        VARCHAR(100)    NOT NULL,
    label       VARCHAR(255)    NOT NULL,
    description VARCHAR(1024)   DEFAULT NULL,
    active      BOOLEAN         NOT NULL
);

CREATE UNIQUE INDEX roles_role_idx ON roles (role);

CREATE TABLE IF NOT EXISTS users_roles_xref (
    userid      INTEGER         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    roleid      INTEGER         NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    PRIMARY KEY (userid, roleid)
);
